# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license = "Assets: All Rights Reserved; Code: GPL-3.0"
issueTrackerURL="https://github.com/RazorDevs/Deep-Aether/issues"
[[mods]]
logoFile="deep_aether.png"
modId="deep_aether"
version="${file.jarVersion}"
displayName="Deep Aether"
displayURL="https://github.com/RazorDevs/Deep-Aether/wiki"
credits="Unofficial Add-on to the Aether mod. Textures by 345boneshoss and Aethyus. Code by TunefulTurntip and darksonic300. A mod by the Team Razor." #optional
# A text field displayed in the mod UI
authors="Team Razor: 345boneshoss, Aethyus, AwesomeGames, Egg, EnderCristy, darksonic300, TunefulTurntip, and the other members." #optional
description='''
Deep Aether is an unofficial addon for the Aether Mod which aims to add extra content to the Aether Dimension in a similar fashion to the 1.16 Nether Expansion update.
Extra content includes new blocks, items, plants, biomes, trees, mobs, and more!
Created by RazorDevs!
'''
[[dependencies.deep_aether]]
modId="forge"
mandatory=true
versionRange="[43.1,)"
ordering="NONE"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side="BOTH"

[[dependencies.deep_aether]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2]"
ordering="NONE"
side="BOTH"

[[dependencies.deep_aether]]
modId="aether"
mandatory=true
versionRange="1.0.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.deep_aether]]
modId="geckolib3"
mandatory=true
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.deep_aether]]
modId="aeroblender"
mandatory=true
versionRange="[0,)"
ordering="NONE"
side="BOTH"

